using System.Security.Cryptography;
using Jellyfin.Plugin.Overcoat.Services;
using SkiaSharp;

const int W=1600, PW=250, PH=375;
var cli=Args(args); if(!cli.TryGetValue("input",out var input)||!cli.TryGetValue("output",out var output)){Console.Error.WriteLine("Usage: Showcase --input <clean-posters> --output <directory>");return 2;}
input=Path.GetFullPath(input); output=Path.GetFullPath(output); if(output==input||output.StartsWith(input+Path.DirectorySeparatorChar,StringComparison.Ordinal))throw new ArgumentException("Output must be separate from input.");
var names=new[]{"game-of-thrones","friends","the-office","breaking-bad","stranger-things","the-sopranos"};
var files=names.ToDictionary(n=>n,n=>Find(input,n)); var hashes=files.Values.ToDictionary(p=>p,Hash); Directory.CreateDirectory(output);
using var renderer=new OverlayRenderer(); var compositor=new BadgeCompositor();
SKBitmap Render(string name,string text,OverlayRenderer.BannerOptions? opt=null,BadgeCompositor.BadgeLayout? layout=null,params string[] badges){using var src=SKBitmap.Decode(files[name])??throw new InvalidDataException(files[name]);var p=Cover(src,PW,PH);renderer.DrawStatusBanner(p,text,opt??new(){IconKey=text.Split(' ')[0]});if(badges.Length>0)compositor.Apply(renderer,p,new HashSet<string>(badges),layout??BadgeCompositor.BadgeLayout.Default);return p;}

Plate("showcase-hero.png",760,c=>{Header(c,"OVERCOAT","Smart poster overlays for Jellyfin",74);var s=new[]{"NEW","AIRING SUN","RETURNING 8/16","ENDED","CANCELED","AIRING"};for(int i=0;i<6;i++){using var p=Render(names[i],s[i]);Card(c,p,40+i*258,230,Title(names[i]),s[i]);}});
Plate("showcase-statuses.png",690,c=>{Header(c,"STATUS BANNERS","Five clear states · sample treatments captured July 22, 2026",52);var rows=new[]{("game-of-thrones","NEW"),("friends","AIRING SUN"),("the-office","RETURNING 8/16"),("breaking-bad","ENDED"),("stranger-things","CANCELED")};for(int i=0;i<5;i++){using var p=Render(rows[i].Item1,rows[i].Item2);Card(c,p,110+i*282,205,Title(rows[i].Item1),rows[i].Item2);}});
Plate("showcase-styles.png",690,c=>{Header(c,"ONE BANNER, THREE MOODS","Solid, frosted glass, and neon",52);var os=new[]{new OverlayRenderer.BannerOptions{Style="solid",IconKey="ENDED"},new(){Style="glass",GlassBlur=75,GlassTintStrength=55,IconKey="ENDED"},new(){Style="neon",NeonGlow=90,IconKey="ENDED"}};for(int i=0;i<3;i++){using var p=Render("breaking-bad","ENDED",os[i]);Card(c,p,310+i*350,205,new[]{"SOLID","FROSTED GLASS","NEON"}[i],"Same clean source poster");}});
Plate("showcase-controls.png",1080,c=>{Header(c,"MAKE IT YOURS","Major banner controls, represented once each",52);var x=new(string,string,OverlayRenderer.BannerOptions)[]{("PILL · TOP","NEW",new(){Shape="pill",IconKey="NEW"}),("SQUARE · BOTTOM","ENDED",new(){Shape="square",Position="bottom",Font="serif",IconKey="ENDED"}),("DROP · LEFT + SHADOW","AIRING SUN",new(){Shape="drop",Align="left",Shadow=true,IconKey="AIRING"}),("FULL WIDTH · GLASS","RETURNING 8/16",new(){Shape="drop",FullWidth=true,Align="right",Style="glass",GlassTint="#24103A",GlassBlur=80,IconKey="RETURNING"}),("MONO · LARGE · GLOW","CANCELED",new(){Font="mono",FontScale=1.18,Style="neon",NeonGlow=100,IconKey="CANCELED"}),("NO ICON · CUSTOM COLOR","ENDED",new(){ShowIcons=false,Shadow=true,ColorOverride="#6750A4",IconKey="ENDED"})};for(int i=0;i<6;i++){using var p=Render(names[i],x[i].Item2,x[i].Item3);Card(c,p,310+(i%3)*350,195+(i/3)*430,x[i].Item1,x[i].Item2);}});
Plate("showcase-badges.png",760,c=>{Header(c,"CHOOSE THE BADGES EACH LIBRARY GETS","Watch history only · TMDB only · both ribbons · IMDb Top 250",48);var cases=new(string,string[])[]{("WATCH HISTORY ONLY",new[]{BadgeCompositor.WatchHistory}),("TMDB TRENDING ONLY",new[]{BadgeCompositor.TmdbTrending}),("BOTH SIDE RIBBONS",new[]{BadgeCompositor.WatchHistory,BadgeCompositor.TmdbTrending}),("IMDb TOP 250",new[]{BadgeCompositor.ImdbTop250})};for(int i=0;i<4;i++){using var p=Render(new[]{"friends","the-office","breaking-bad","the-sopranos"}[i],"AIRING",new(){Style="solid",Shape="pill",Position="top",IconKey="AIRING"},new(false,i==2?"middle":"top",100,i==2?2:0),cases[i].Item2);Card(c,p,175+i*325,225,cases[i].Item1,i==2?"2% ribbon spacing":"enabled for this library");}});
foreach(var kv in hashes)if(Hash(kv.Key)!=kv.Value)throw new IOException($"Input changed: {kv.Key}"); Console.WriteLine($"Generated 5 plates; {hashes.Count} input hashes unchanged.");return 0;

void Plate(string name,int h,Action<SKCanvas> draw){using var b=new SKBitmap(W,h);using var c=new SKCanvas(b);c.Clear(new SKColor(13,17,23));draw(c);using var im=SKImage.FromBitmap(b);using var d=im.Encode(SKEncodedImageFormat.Png,92);File.WriteAllBytes(Path.Combine(output,name),d.ToArray());}
static void Header(SKCanvas c,string a,string b,float s){using var p=new SKPaint{Color=SKColors.White,IsAntialias=true,TextSize=s,Typeface=SKTypeface.FromFamilyName("sans-serif",SKFontStyle.Bold)};using var q=new SKPaint{Color=new SKColor(163,174,192),IsAntialias=true,TextSize=26};using var line=new SKPaint{Color=new SKColor(126,75,255),StrokeWidth=5};c.DrawText(a,52,88,p);c.DrawText(b,54,132,q);c.DrawLine(54,155,1546,155,line);}
static void Card(SKCanvas c,SKBitmap p,float x,float y,string a,string b){using var path=new SKPath();path.AddRoundRect(new SKRect(x,y,x+PW,y+PH),18,18);c.Save();c.ClipPath(path,SKClipOperation.Intersect,true);c.DrawBitmap(p,x,y);c.Restore();using var q=new SKPaint{Color=SKColors.White,IsAntialias=true,TextSize=20,Typeface=SKTypeface.FromFamilyName("sans-serif",SKFontStyle.Bold)};using var r=new SKPaint{Color=new SKColor(150,161,181),IsAntialias=true,TextSize=16};c.DrawText(a,x,y+PH+31,q);c.DrawText(b,x,y+PH+54,r);}
static SKBitmap Cover(SKBitmap s,int w,int h){var z=Math.Max(w/(float)s.Width,h/(float)s.Height);var sw=w/z;var sh=h/z;var src=new SKRect((s.Width-sw)/2,(s.Height-sh)/2,(s.Width+sw)/2,(s.Height+sh)/2);var d=new SKBitmap(w,h);using var c=new SKCanvas(d);using var p=new SKPaint{FilterQuality=SKFilterQuality.High};c.DrawBitmap(s,src,new SKRect(0,0,w,h),p);return d;}
static string Find(string d,string n)=>new[]{".jpg",".jpeg",".png",".webp"}.Select(e=>Path.Combine(d,n+e)).FirstOrDefault(File.Exists)??throw new FileNotFoundException($"Missing clean poster {n}");
static string Hash(string p)=>Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(p)));
static string Title(string s)=>s.Replace('-',' ').ToUpperInvariant();
static Dictionary<string,string> Args(string[] a){var d=new Dictionary<string,string>();for(int i=0;i<a.Length-1;i+=2)d[a[i].TrimStart('-')]=a[i+1];return d;}
