name: Feature request
description: Suggest an idea for Overcoat
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: What are you trying to do that Overcoat doesn't (yet) support?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How might it look or behave?
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
